# Generated by Django 4.1 on 2023-11-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('property_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('username', 'property_id')},
            },
        ),
    ]
