# Generated by Django 4.1 on 2023-11-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproperty',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
